import Head from 'next/head'
import { Flex, Heading, withAuthenticator } from '@aws-amplify/ui-react'
import { API } from 'aws-amplify'
import { useEffect, useState } from 'react'
import { listRecipes } from '../../src/graphql/queries'
import { ListRecipesQuery } from '@/src/API'
import { GraphQLResult } from '@aws-amplify/api-graphql'
import { BillingPortalLink } from '@/components/BillingPortalLink'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'
import { Recipe } from '@/src/API'
// added by Hui
import { Storage } from 'aws-amplify';
import { useRouter } from 'next/router'

const MyRecipes = ({ user, signOut }: any) => {
	const router = useRouter()
	const [fetchedRecipes, setFetchedRecipes] = useState<
		(Recipe | null)[] | undefined
	>([])
	// added by Hui
	const [imageUrls, setImageUrls] = useState<Record<string, string>>({})
	useEffect(() => {
		async function listRecipesForUser() {
			const res = (await API.graphql({
				query: listRecipes,
			})) as GraphQLResult<ListRecipesQuery>

			console.log(res.data?.listRecipes)
			setFetchedRecipes(res.data?.listRecipes)

			// Fetch image URLs for all recipes added by Hui
			if (res.data?.listRecipes) {
				const urls: Record<string, string> = {}
				
				for (const recipe of res.data.listRecipes) {
					if (recipe && recipe.coverImage) {
						try {
							const url = await Storage.get(recipe.coverImage)
							urls[recipe.id] = url
						} catch (error) {
							console.error(`Error getting URL for image ${recipe.coverImage}:`, error)
						}
					}
				}
				
				setImageUrls(urls)
			}			
		}

		listRecipesForUser()
	}, [])

	return (
		<>
			<Head>
				<title>Lychnis Realty</title>
				<meta name="description" content="Generated by Otterlicious" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Flex direction={'column'} height={'100vh'} width={'100vw'}>
				<Navbar isAuthPage />

				<Flex
					justifyContent={'center'}
					alignItems={'center'}
					direction="column"
					flex={1}
				>
					<Heading level={2} textAlign={'center'}>
						Welcome to my projects
					</Heading>
					<BillingPortalLink email={user.attributes.email} />
					{fetchedRecipes?.map((fr) => {
						if (fr) {
							return (
								<div key={fr.id} className="card w-96 bg-base-100 shadow-xl">
									<figure>
										<img
											src={imageUrls[fr.id]}
											alt={fr.title}
										/>
									</figure>
									<div className="card-body">
										<h2 className="card-title">
											{fr.title}
											<div className="badge badge-secondary">Status: NEW</div>
										</h2>
										<p>{fr.description}</p>
										<div className="card-actions justify-end">
											<div className="badge badge-outline">Project Name</div>
											<button 
												className="btn btn-primary btn-sm"
												onClick={() => router.push(`/my-recipes/update/${fr.id}`)}
											>
												Edit
											</button>
										</div>
									</div>
								</div>
							)
						}
					})}
				</Flex>
				<Footer />
			</Flex>
		</>
	)
}

export default withAuthenticator(MyRecipes, { signUpAttributes: ['email'] })